### ISSUE TITLE
[FEAT] 멋사 6주차 과제🦁

### ISSUE THREAD

**Issue by ahyeon-github** [Likelion-at-SMWU-10th/LimAHyeon#10]
## 📌  Feature Issue

나만의 다이어리 만들기 6주차 과제
- [ ] 프로젝트 : ahyeondiary 앱 이름: diaryapp 으로 바꿔서 과제를 했습니다.

- [ ] 앱 2개 이상 만들어서 url mapping 사용 - 앱 이름은 각각 diaryapp, record로 url mapping을 사용하였습니다. 


## 📝  To-do

- [ ] django 강의 수강하기
