### ISSUE TITLE
[FEAT] 멋사 7주차 과제🦁

### ISSUE THREAD

**Issue by ahyeon-github** [Likelion-at-SMWU-10th/LimAHyeon#13]
## 📌  Feature Issue

- [ ] 코드라이언 강의 수강
- [ ]  6주차 과제인 ‘나만의 다이어리’에 7주차에 배운 model 추가하기

## 📝  To-do

- [ ] 8주차 과제 진행
- [ ] 장고 복습하기
