### ISSUE TITLE
[FEAT] 멋사 8차 과제🦁

### ISSUE THREAD

**Issue by ahyeon-github** [Likelion-at-SMWU-10th/LimAHyeon#16]
## 📌  Feature Issue

- [ ] 6주차 과제에 회원가입, 로그인, 로그아웃 추가하기
- [ ] community와 blog 합치기
- [ ] 이 때 사용자가 회원가입 따로, 로그인 따로 하게 하기

## 📝  To-do

- [ ] 장고 복습
